spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/apdata
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:category_insert_20200407.sql,classpath:product_insert_20200407.sql
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    hibernate.type.descriptor.sql.BasicBinder: trace

